version: "3"

services:
  App1:
    container_name: contenedorApacheApp1
    image: php:7-apache
    volumes:
      - ./App1:/var/www/html
    expose:
      - 80
    ports:
      - 5000:80

  App2:
    container_name: contenedorNginxApp2
    image: nginx
    volumes:
      - ./App2:/usr/share/nginx/html
      - ./App2:/etc/nginx/conf.d/Nginx
    expose:
      - 80
    ports:
        - 5100:80
    environment:
      - NGINX_HOST=127.0.0.2
      - NGINX_PORT=80

  App3:
    container_name: contenedorApacheApp3
    image: php:7-apache
    volumes:
      - ./App3:/var/www/html
    expose:
      - 80
    ports:
      - 5200:80
